/**
 * eula.ts - 利用規約（EULA）の全文と版管理
 *
 * 正本: GitでIgnoreしたいファイル達/要件まとめ/配布公開準備その2/15_ライセンスとEULA整備.md 3章。
 * 文面を改定したら EULA_VERSION を上げること（版が変わると全ユーザーに再同意を求める）。
 * en 版は配布物 EULA.en.md と文面を同期させること。規約の正文は日本語版であり、
 * 相違がある場合は日本語版が優先する（en 版の追加は文面改定ではないため版は据え置き）。
 */

// 同意記録に保存する版。文面改定日を版として使う。
export const EULA_VERSION = '2026-07-06';

// pwa-settings.json に保存する同意記録のキー
export const EULA_CONSENT_KEY = 'eulaConsent';

export interface EulaConsent {
    version: string;
    acceptedAt: string; // ISO 8601
}

export const EULA_TITLE_JA = 'AlSlime 利用規約';

export const EULA_FULL_TEXT_JA = `第1条（定義）
本規約は、AlSlime（以下「本ソフトウェア」）の利用条件を定めるものです。本ソフトウェアは、利用者が自ら契約・導入した外部の AI サービスおよびローカルツール（以下「外部AIサービス」）へ接続するための、ローカルで動作する創作支援ツールです。

第2条（年齢要件）
本ソフトウェアは、18歳以上の方のみ利用できます。18歳未満の方は利用できません。この年齢要件は、接続先の外部AIサービスの出力内容を開発者が管理できず、不正確または不適切な内容が生成され得ることを踏まえた予防的措置です。

第3条（利用許諾）
開発者は、利用者に対し、本規約の遵守を条件として、本ソフトウェアを利用者自身の端末で使用する非独占的な権利を許諾します。配布形態ごとの複製・改変・再配布の可否は、同梱のライセンス文書（LICENSE）に従います。

第4条（外部AIサービスと生成物）
1. 本ソフトウェアの出力（文章・画像等）は、利用者が接続した外部AIサービスが生成するものであり、開発者は生成の内容に関与せず、これを取得・保存・閲覧する手段を持ちません。
2. 利用者は、接続する外部AIサービスの利用規約・ポリシーを自らの責任で遵守するものとします。
3. 生成物に関する権利および責任は、適用される法令および外部AIサービスの規約の定めに従い、利用者に帰属します。

第5条（禁止事項）
利用者は、本ソフトウェアを法令に違反する目的で利用してはなりません。また、配布形態のライセンス文書で認められる場合を除き、本ソフトウェアの解析（リバースエンジニアリング）、改変、再配布を行ってはなりません。

第6条（無保証）
本ソフトウェアは現状有姿（AS IS）で提供されます。開発者は、動作の正確性・完全性・特定目的への適合性について、いかなる保証も行いません。外部AIサービスの出力は不正確または不適切な場合があります。本ソフトウェアは医療・カウンセリング・緊急対応その他の専門的助言を提供するものではありません。

第7条（責任の制限）
開発者は、本ソフトウェアの利用または利用不能から生じた損害について、法令上許容される最大限の範囲で責任を負いません。ただし、開発者の故意または重過失による損害についてはこの限りではありません。

第8条（プライバシー）
本ソフトウェアは、会話内容・生成物・キャラクター設定を開発者へ送信しません。支援者向け機能の認証を利用する場合に限り、GitHub アカウント識別子と支援状態のみが認証サーバーで扱われます。

第9条（規約の変更）
開発者は、必要に応じて本規約を変更できます。変更後の規約は、配布物への同梱または公開リポジトリへの掲載をもって効力を生じます。

第10条（準拠法・管轄）
本規約は日本法に準拠し、本規約に関する紛争は、開発者の住所地を管轄する裁判所を第一審の専属的合意管轄裁判所とします。`;

export const EULA_TITLE_EN = 'AlSlime Terms of Use';

export const EULA_FULL_TEXT_EN = `Article 1 (Definitions)
These Terms set forth the conditions for use of AlSlime (the "Software"). The Software is a locally-running creative support tool for connecting to external AI services and local tools that the user has contracted for and installed on their own (collectively, "External AI Services").

Article 2 (Age Requirement)
The Software may be used only by persons 18 years of age or older. Persons under 18 may not use the Software. This age requirement is a precautionary measure reflecting the fact that the developer cannot control the output of the External AI Services the user connects, and such output may be inaccurate or inappropriate.

Article 3 (Grant of License)
The developer grants the user a non-exclusive right to use the Software on the user's own device, subject to compliance with these Terms. Whether copying, modification, and redistribution are permitted for each distribution form is governed by the bundled license document (LICENSE).

Article 4 (External AI Services and Generated Content)
1. The output of the Software (text, images, etc.) is generated by the External AI Services the user connects. The developer is not involved in the content of such generation and has no means to obtain, store, or view it.
2. The user shall comply, at the user's own responsibility, with the terms of use and policies of the External AI Services the user connects.
3. Rights to and responsibility for generated content belong to the user, in accordance with applicable laws and the terms of the External AI Services.

Article 5 (Prohibited Acts)
The user shall not use the Software for any purpose that violates applicable laws. Except as permitted by the license document of the applicable distribution form, the user shall not analyze (reverse engineer), modify, or redistribute the Software.

Article 6 (No Warranty)
The Software is provided AS IS. The developer makes no warranty of any kind as to the accuracy or completeness of its operation or its fitness for any particular purpose. Output from External AI Services may be inaccurate or inappropriate. The Software does not provide medical, counseling, emergency-response, or any other professional advice.

Article 7 (Limitation of Liability)
To the maximum extent permitted by applicable law, the developer shall not be liable for any damages arising from the use of, or inability to use, the Software; provided, however, that this shall not apply to damages caused by the developer's willful misconduct or gross negligence.

Article 8 (Privacy)
The Software does not transmit conversation content, generated content, or character settings to the developer. Only when the user uses authentication for supporter features, the user's GitHub account identifier and support status alone are handled by the authentication server.

Article 9 (Amendment of the Terms)
The developer may amend these Terms as necessary. Amended Terms take effect upon being bundled with a distribution or posted to the public repository.

Article 10 (Governing Law and Jurisdiction)
These Terms are governed by the laws of Japan, and the court having jurisdiction over the developer's place of residence shall be the exclusive agreed court of first instance for any dispute concerning these Terms.`;
